version: '3'

services:
  client:
    build: ./client
    ports:
      - "80:4200"
    volumes:
      - ./client:/usr/src/app
  server:
    build: ./server
    restart: always
    ports:
      - "8080:8080"
    environment:
      - MONGO_URL=mongodb://database/CustomersDatabase
    links:
      - database
    depends_on:
      - database
  database:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./init-database-data.json:/usr/src/app/init-database-data.json
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh